version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  # unbound:
  #   image: "mvance/unbound:latest"
  #   container_name: unbound
  #   restart: unless-stopped
  #   hostname: "unbound"
  #   volumes:
  #     - "./unbound:/opt/unbound/etc/unbound/"
  #   networks:
  #     private_network:
  #       ipv4_address: 10.2.0.200

  wireguard:
    depends_on: [pihole]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne # Change to your timezone
      - SERVERPORT=51820
      #- SERVERURL=my.ddns.net #optional - For use with DDNS (Uncomment to use)
      - PEERS=2 # How many peers to generate for you (clients)
      - PEERDNS=10.2.0.100 # Set it to point to pihole
      - INTERNAL_SUBNET=10.6.0.0
      
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    dns:
      - 10.2.0.100 # Points to pihole
      # - 10.2.0.200 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.3

  pihole:
    # depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      - 1.1.1.2 # cf
    environment:
      TZ: "Australia/Melbourne"
      WEBPASSWORD: "$2b$10$8K1p/a0dR1LXMIgoEDFrwOfgqwGzKxqQYwJ1YwYqKxYqKxYqKxYqK" # This is an encrypted password for "wirehole"
      ServerIP: 10.2.0.100 # Internal IP of pihole
      DNS1: 1.1.1.2 # Cloudflare malware blocking
      DNS2: 1.1.1.3 # Cloudflare malware blocking
    # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.2.0.100
